### ISSUE TITLE
theano problem.

### ISSUE THREAD

**Issue by osok** [fastai/courses#237]
I had previously been trying to use python 3.10 and had issues with other libraries see other issues listed.  So I thought I would try 3.9 and 3.11 versions of python.  Now when I use pip to install the requirements for courses I get this error

```
Using cached Theano-0.5.0.zip (1.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\michael\AppData\Local\Temp\pip-install-udcu9o9k\theano_e0dbfd1a8cc6447e8e35d2e6851686f2\setup.py", line 119
          except Exception, e:
                 ^^^^^^^^^^^^
      SyntaxError: multiple exception types must be parenthesized
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

I'm using annaconda, so with each new environment there is no other libraries to conflict with.  

I'm betting that if I try again with 3.10 I'll see the same error.  This means that something in that libraries latest version is breaking.

This is what especially dislike about python.  All the different versions of python and different versions of libraries. 

 requirements.txt should IMO have exact versions at the time of creation, when everything worked together, and a reference to exactly what version major and minor of python that was used.

Can someone assist?  I feel like an **idiot** here.  I have A CS degree and 30 years of development back ground.  Python is the one of the languages I have not taken the time to learn beause I can do most stuff in Java, Go, C, C++ or other historical languages not worth mentioning.  I get that it is something I have to overcome to work with AI, so I will.  

I'm thrilled that this course and others exist and are free.  When I hear hundreds of thousands of people have taken it, it doesn't matter all the cool fringe stuff that I have done in the past, when I cannot get  it to work and I don't get any responses on issues, I feel like an **idiot**.

Unfortunately for me this is not something I can just forget and move on to the next shiny thing.  I need this training.  I would pay for support if I could but I cannot.

In the words of a toddler fed wasabi....

'help'

**Comment by osok** [comment]
Well, I think I found the issue.  I just installed Anaconda about a three weeks ago.  It says it is version 4.12.0 and the current version is 23.5.0.  I looked it when I noticed some of the libraries that were in the requirements doc were not the latest.

Letting a little frustration out can clear the mind.   I could go back and edit that post, but maybe it'll help the next so frustrated individual.

**Comment by osok** [comment]
upgrading anaconda helped.
